### ISSUE TITLE
Boolean Arguments

### ISSUE THREAD

**Issue by eduardofavarin** [charlesdevandiere/graphql-client-extensions#15]
How can I add boolean arguments?

`var query = new Query<Orders>("orders").AddArguments(new {
                    imported = true
                }).AddField(h => h.total);`

After run this code snippet, the following exception is thrown

![image](https://user-images.githubusercontent.com/11446442/59947946-fde76c80-9444-11e9-955a-ba90ce95ad11.png)

**Comment by charlesdevandiere** [comment]
@eduardofavarin  thanks for this issue!

I fixed it in PR #16!

Tell me if it works for you :blush:
