### ISSUE TITLE
Query<T>.Build() throws ArgumentException when building query with "nested" arguments

### ISSUE THREAD

**Issue by reureu** [charlesdevandiere/graphql-client-extensions#23]
Hi Charles,

I was playing around with GraphQL.Client.Extensions when I bumped into the following problem:

I need to create the following query:
```
dummy
{
	Key
	Values(match:\"blabla\")
}
```

which is meant to be a well-formed GraphQL query which GraphQL-Servers are able to interpret.

When I execute the following code:
```
var query = new Query<DummyDto>("dummy")
                .AddField(dto => dto.Key)
                .AddField(dto => dto.Values, sq => sq.AddArgument("match", "blabla"));

query.Build();
```
Build() throws the following exception

```
System.ArgumentException : Must have a one or more 'Select' fields in the Query
   at GraphQL.Client.Extensions.Query`1.Build()
   at GraphQL.Client.Extensions.QueryStringBuilder.AddFields[TSource](IQuery`1 query)
   at GraphQL.Client.Extensions.QueryStringBuilder.Build[TSource](IQuery`1 query)
   at GraphQLExtensionsTest01.QueryTest.AddArgument_TestInHierarchicalQuery()
```
I have attached a test project that shows this behaviour.

Your help would be greatly appreciated.

[GraphQLExtensionsTest01.zip](https://github.com/charlesdevandiere/graphql-client-extensions/files/4204664/GraphQLExtensionsTest01.zip)

Kind regards,
JY

**Comment by Alexandre-Nourissier** [comment]
L. 242 of QueryOf{T}, I think a this. is missing before the SelectList.Count()

**Comment by Alexandre-Nourissier** [comment]
Indeed, there is an issue with the way subqueries are handled. 
Right now you can only subquery on a complex type because the QueryBuilder needs at least one selected field on the subject of the query. But if the subject is a string or an int, there is no such field for you to specify. 
I will look into it and see if there an elegant way to support this scenario.

**Comment by Alexandre-Nourissier** [comment]
> I will look into it and see if there an elegant way to support this scenario.

Basically we need to check if the query subject's type is a scalar type as described here https://graphql.org/learn/schema/#scalar-types.
If it is, we don't add the fields. 
https://github.com/charlesdevandiere/graphql-client-extensions/blob/c49e87f931d4f33d3d34f04251b21826c6565187/src/GraphQL.Client.Extensions/QueryStringBuilder.cs#L219-L224

**Comment by Alexandre-Nourissier** [comment]
But the trick is that there can be custom scalar types. So we actually need 2 ways to handle this scenario:
* If default scalar type, the user don't have to add anything, it works as @reureu expected.
* If custom scalar type, the user will need to be able to add a field or add a flag on this subject, an additional method on IQueryOf{T} maybe @charlesdevandiere?

**Comment by charlesdevandiere** [comment]
@reureu @Alexandre-Nourissier thanks ! I'm working on it 😉

**Comment by charlesdevandiere** [comment]
Fixed in release [2.1.0](https://github.com/charlesdevandiere/graphql-client-extensions/releases/tag/2.1.0).

Enjoy !

**Comment by reureu** [comment]
Hi @charlesdevandiere & @Alexandre-Nourissier,

Thank you very much for your quick answers.

Sorry for being fussy, but it is my understanding that it should throw an exception if the argument refers to an object type, and the user does no specify which property is expected.

Consequently, the following test expects an ArgumentException, as it is wrong to specify an argument on "SubObject" without specifying which property is expected.

```
[Test]
public void AddArgument_TestExceptionInHierarchicalQuery()
{
	var query = new Query<DummyDto>("dummy")
		.AddField(dto => dto.Key)
		.AddField(dto => dto.SubObject, sq => sq.AddArgument("match", "blabla"));

	Assert.That(() => query.Build(), Throws.Exception.TypeOf<ArgumentException>());
}

private class DummyDto
{
	public string Key { get; set; }

	public string[] Values { get; set; }

	public SubDto SubObject { get; set; }
}

private class SubDto
{
	public int Value { get; set; }
}

```
The Test 'AddArgument_TestExceptionInHierarchicalQuery' fails with GraphQL.Client.Extensions version 2.1.0.

Just as info, I have created a [repository](https://github.com/reureu/GraphQL.Client.Extensions.Test
) with these tests.

Kind regards,
JY

**Comment by charlesdevandiere** [comment]
@reureu Yes you'r right. But it's possible to create custom scalar types in a GraphQL Server. So I prefer to not verify the query type to keep graphql-client-extensions simple and easy to use 🙂.
