### ISSUE TITLE
Adding a Json as argument value in AddArgument()

### ISSUE THREAD

**Issue by gopala000** [charlesdevandiere/graphql-client-extensions#31]
One of the service that I consume expect a Json as an argument value. If I pass a Json value, the library throws exception. I s there a workaround?

**Comment by charlesdevandiere** [comment]
Hi @gopala000! I upgraded GraphQL.Query.Builder 1.6.0. You can now pass a JSON value.

https://github.com/charlesdevandiere/graphql-client-extensions/releases/tag/3.2.1
